### ISSUE TITLE
Error when running on another port

### ISSUE THREAD

**Issue by muhammedMoussa** [kitze/custom-react-scripts#103]
### Is this a bug report?

yes

### Can you also reproduce the problem with npm 4.x?

i think this issue not related to npm ver

### Environment

1. `node -v`: 6.11.2
2. `npm -v`: 3.10.10
3. `yarn --version` : 0.27.5
4. `npm ls react-scripts`: 

Then, specify:

1. Operating system: Linux Mint
2. Browser and version (not relevant):

### Steps to Reproduce

(Write your steps here:)

1. try to `yarn start` inside project.
2. show :3000 is busy, and suggest another (:3001) 
3. got error

### Expected Behavior

```
to be executed: node bin/server 
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "development". +4ms
  app:config Found overrides, applying to default configuration. +2ms
  app:webpack:config Creating configuration. +906ms
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +1ms
  app:server Enable webpack dev and HMR middleware +124ms
  app:bin:server Server is now running at http://localhost:3001. +64ms
webpack: wait until bundle finished: /__webpack_hmr
webpack built de47ff4a6449d2ec1892 in 18341ms
Hash: de47ff4a6449d2ec1892
Version: webpack 1.15.0
Time: 18341ms
                             Asset     Size  Chunks             Chunk Names
       app.de47ff4a6449d2ec1892.js  8.12 MB       0  [emitted]  app
    vendor.de47ff4a6449d2ec1892.js   392 kB       1  [emitted]  vendor
   app.de47ff4a6449d2ec1892.js.map  9.67 MB       0  [emitted]  app
vendor.de47ff4a6449d2ec1892.js.map   462 kB       1  [emitted]  vendor
                       favicon.ico  5.43 kB          [emitted]  
                        index.html  3.54 kB          [emitted]  
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  581 kB       0       
webpack: Compiled successfully.

```

### Actual Behavior

```
Starting the development server...

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /my-app/public ENOSPC
    at exports._errnoException (util.js:1020:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (my-app/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (my-app/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (my-app/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (my-app/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (my-app/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (my-app/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
error Command failed with exit code 1.

```

**Comment by jetpack3331** [comment]
Any progress?
