### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by janterlaak** [kitze/custom-react-scripts#104]
after installation and creating a project

yarn start 

/Users/j/test/myapp/node_modules/custom-react-scripts/scripts/start.js:21
  throw err;
  ^

RangeError: Invalid string length
    at Object.stringify (native)
    at serializeMap (/Users/j/test/myapp/node_modules/inspectpack/lib/utils/cache.js:26:15)
    at getCacheFilePath.then.filePath (/Users/janterlaak/test/myapp/node_modules/inspectpack/lib/utils/cache.js:93:27)
error Command failed with exit code 1.$

**Comment by janterlaak** [comment]
Removing the last line from the .env file does the trick

**Comment by OshotOkill** [comment]
Got the same error too:

<img width="1300" alt="2017-09-14 5 37 44" src="https://user-images.githubusercontent.com/6079112/30422787-932efb00-9906-11e7-8734-0a5b7dd85981.png">

It suddenly happened while coding. It's really weird since I don't do anything to `package.json` or any configuration files. I commented most of my code and only left `index.js`, however the error still happened.

**Comment by janterlaak** [comment]
Open your .env file and remove the last line of the configutation.  Save the file and run again

**Comment by OshotOkill** [comment]
@janterlaak That works.

I dig out a lot bit more and find out the real problem is `REACT_APP_WEBPACK_DASHBOARD` in `.env` file. It seems the internal module `inspectpack` is broken somehow and effects the webpack dashboard. After remove it the dev-server would work fine.
