### ISSUE TITLE
Jest fails on pre-processed CSS projects - even in the default-generated app

### ISSUE THREAD

**Issue by igorsantos07** [kitze/custom-react-scripts#49]
### Description
The basic Jest test fails, stumbling upon Less/Sass code.

### Expected behavior
Test should pass - it's the default one, after all.

### Actual behavior
_Project paths were changed for brevity._

```
  ● Test suite failed to run

    /var/project/src/styles/consolidator.less:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@import "_variables";
                                                                                             ^
    SyntaxError: Invalid or unexpected token
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:316:10)
      at Object.<anonymous> (src/screens/Screen1.jsx:6:27)
```

The default application generated also fails with this message:
```
    /var/my-app/src/App.less:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.App {
```

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls react-scripts` (if you haven’t ejected): didn't eject
2. `node -v`: 6.9.1
3. `npm -v`: 3.10.8

Then, specify:

1. Operating system: Linux Mint 18 Sarah
2. Browser and version: CLI

### Reproducible Demo
It seems the default installation already breaks tests.

**Comment by igorsantos07** [comment]
Closed by #52.
