### ISSUE TITLE
is custom-react-scripts compatible with react-loadable

### ISSUE THREAD

**Issue by jason-henriksen** [kitze/custom-react-scripts#99]
### Is this a bug report?
Yes?  Not sure if its in your power to affect or not.

I'm trying to put a react-loadable component into my react-router system and if fails to compile, but due to a problem in a file I don't know about.

Creating an optimized production build...
Failed to compile.

Module parse failed: C:\src\MQ\MQ-UI\node_modules\babel-loader\index.js?{"babelrc":false,"presets":["C:\\src\\MQ\\MQ-UI\\node_modules\\babel-preset-rea
ct-app\\index.js","C:\\src\\MQ\\MQ-UI\\node_modules\\babel-preset-stage-0\\lib\\index.js"],"plugins":["C:\\src\\MQ\\MQ-UI\\node_modules\\babel-plugin-t
ransform-decorators-legacy\\lib\\index.js"]}!C:\src\MQ\MQ-UI\node_modules\eslint-loader\index.js!C:\src\MQ\MQ-UI\src\UI\Router\Routes.jsx Unexpected to
ken (153:23)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (153:23)
    at Parser.pp$4.raise (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:839:33)
    at Parser.pp$1.parseStatement (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:699:34)
    at Parser.pp$1.parseBlock (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:2105:24)
    at Parser.pp$1.parseFunction (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1065:10)
    at Parser.pp$3.parseExprAtom (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1810:19)
    at Parser.pp$3.parseExprSubscripts (C:\src\MQ\MQ-UI\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mq4@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mq4@0.1.0 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mq4 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mq4
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mq4
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\MQ\MQ-UI\npm-debug.log

### Can you also reproduce the problem with npm 4.x?

import React from 'react';
import Loadable from 'react-loadable';
import RegisterFloristPage from '../Pages/App/Login/RegisterFloristPage';
//const RegisterFloristPage = Loadable({ loader: () => import('../Pages/App/Login/RegisterFloristPage') })

If I comment out line 3 and uncomment line 4 I get the stack trace.

    npm -v
3.10.10

( I started working on this project last November, but I'm not sure how to safely upgrade.)

### Environment

1. `node -v`: 
v6.10.3

2. `npm -v`:
3.10.10

4. `npm ls react-scripts` (if you haven’t ejected): 
npm ERR! code 1
PS C:\src\MQ\MQ-UI> npm ls custom-react-scripts
custom-react-scripts@0.0.21

Then, specify:

1. Operating system: Windows 10

**Comment by jason-henriksen** [comment]
I didn't mean to submit that yet, I realized how far out of date I am.  

Can I just update custom-react-scripts and that will correctly update the dependencies?

**Comment by jason-henriksen** [comment]
Just to be clear:  with a separate app that was created recently, code from react-loadable works just fine. 
I'm going to get my really old application up to date and I expect it will go smoothly from there.
